services:
  - type: web
    name: rey-vogue
    runtime: python
    region: ohio
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DATABASE_URL
        fromDatabase:
          name: rey_vogue_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REDIS_URL
        fromService:
          name: rey-vogue-redis
          type: redis
          property: connectionString
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@reyvogue.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: PORT
        value: "8000"

  - type: redis
    name: rey-vogue-redis
    ipAllowList: []
    plan: free
    region: ohio

databases:
  - name: rey_vogue_db
    databaseName: rey_vogue
    plan: free
    region: ohio 